"""auto initial schema

Revision ID: 23b79da28667
Revises: 8c636061c20b
Create Date: 2026-03-23 17:15:18.219847

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
from app.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = '23b79da28667'
down_revision: Union[str, None] = '8c636061c20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('integrations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('meetings',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('organizer_id', GUID(length=36), nullable=True),
    sa.Column('attendee_ids', sa.JSON(), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_path', sa.String(length=500), nullable=True),
    sa.Column('recording_size_mb', sa.Float(), nullable=True),
    sa.Column('recording_consent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('transcription_status', sa.String(length=50), nullable=True),
    sa.Column('analysis_status', sa.String(length=50), nullable=True),
    sa.Column('agenda', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_decisions', sa.JSON(), nullable=True),
    sa.Column('discussion_topics', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('meeting_quality_score', sa.Float(), nullable=True),
    sa.Column('speaking_time', sa.JSON(), nullable=True),
    sa.Column('participation_score', sa.JSON(), nullable=True),
    sa.Column('interruption_count', sa.Integer(), nullable=True),
    sa.Column('silence_duration_minutes', sa.Float(), nullable=True),
    sa.Column('meeting_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_external_id'), 'meetings', ['external_id'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_start'), 'meetings', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('action_items',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('owner_id', GUID(length=36), nullable=True),
    sa.Column('collaborator_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('blocked_by', sa.JSON(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('extracted_from_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('reminder_sent_48h', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_24h', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_overdue', sa.Boolean(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=True),
    sa.Column('external_task_id', sa.String(length=255), nullable=True),
    sa.Column('external_task_url', sa.String(length=500), nullable=True),
    sa.Column('integration_type', sa.String(length=50), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('item_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_due_date'), 'action_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_owner_id'), 'action_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('alternatives_considered', sa.JSON(), nullable=True),
    sa.Column('decision_type', sa.String(length=50), nullable=True),
    sa.Column('is_reversible', sa.Boolean(), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('decision_maker_ids', sa.JSON(), nullable=True),
    sa.Column('affected_user_ids', sa.JSON(), nullable=True),
    sa.Column('affected_team', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('implementation_deadline', sa.DateTime(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('outcome_met_expectation', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_meeting_id'), 'decisions', ['meeting_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.String(length=100), nullable=True),
    sa.Column('speaker_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', GUID(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('contains_question', sa.Boolean(), nullable=True),
    sa.Column('contains_action_item', sa.Boolean(), nullable=True),
    sa.Column('contains_decision', sa.Boolean(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('transcript_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_meeting_id'), 'transcripts', ['meeting_id'], unique=False)
    op.create_table('action_item_updates',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('action_item_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('update_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_item_updates_action_item_id'), 'action_item_updates', ['action_item_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('meeting_id', GUID(length=36), nullable=False),
    sa.Column('user_id', GUID(length=36), nullable=False),
    sa.Column('transcript_id', GUID(length=36), nullable=True),
    sa.Column('mention_type', sa.String(length=50), nullable=False),
    sa.Column('mentioned_text', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('full_context', sa.Text(), nullable=True),
    sa.Column('is_action_item', sa.Boolean(), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=True),
    sa.Column('is_decision', sa.Boolean(), nullable=True),
    sa.Column('is_feedback', sa.Boolean(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('notification_read', sa.Boolean(), nullable=True),
    sa.Column('notification_read_at', sa.DateTime(), nullable=True),
    sa.Column('user_responded', sa.Boolean(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('mention_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_meeting_id'), 'mentions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_mentions_user_id'), 'mentions', ['user_id'], unique=False)
    op.create_table('transcript_words',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('transcript_id', GUID(length=36), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_words_transcript_id'), 'transcript_words', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_words_transcript_id'), table_name='transcript_words')
    op.drop_table('transcript_words')
    op.drop_index(op.f('ix_mentions_user_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_meeting_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_action_item_updates_action_item_id'), table_name='action_item_updates')
    op.drop_table('action_item_updates')
    op.drop_index(op.f('ix_transcripts_meeting_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_decisions_meeting_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_owner_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_due_date'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_start'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_external_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
